services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "4096:3306"  # Map host port 4096 to container port 3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
